#!/bin/bash


stty -echo
#задаем пароль пользователя pi
echo
echo -e -n "\033[1;33mEnter password user pi (введите пароль пользователя pi) > \033[0m"
read pass2
stty echo
echo ""
apt update -y
apt upgrade -y
apt install -y python-pip python-dev python-setuptools python-virtualenv git libyaml-dev build-essential virtualenv mc
useradd -m -d /home/pi pi -p $pass2
usermod -a -G sudo pi
usermod -a -G tty pi
usermod -a -G dialout pi
su pi -c 'virtualenv /home/pi/OctoPrint'
su pi -c '/home/pi/OctoPrint/bin/pip install OctoPrint'
su pi -c '/home/pi/OctoPrint/bin/octoprint' &

wget -O /etc/init.d/octoprint https://raw.githubusercontent.com/immortalserg/OctoPrintInstall/master/init/octoprint
wget -O /etc/default/octoprint https://raw.githubusercontent.com/immortalserg/OctoPrintInstall/master/octoprint
su pi -c 'wget -O /home/pi/.octoprint/plugins/ https://raw.githubusercontent.com/immortalserg/OctoPrintInstall/master/rewrite_wait_to_busy.py'
su pi -c 'wget -O /home/pi/.octoprint/ https://raw.githubusercontent.com/immortalserg/OctoPrintInstall/master/config.yaml'


chmod +x /etc/init.d/octoprint
update-rc.d octoprint defaults
sudo hostnamectl set-hostname octoprint.lan
sudo echo "127.0.0.1 octoprint.lan" >> /etc/hosts
sudo echo "127.0.0.1 octoprint" >> /etc/hosts
echo "overlays=analog-codec i2c0 i2c1 spi-spidev uart1 uart2 uart3" | tee -a /boot/armbianEnv.txt
echo "pi ALL=NOPASSWD: /sbin/shutdown" | sudo tee -a /etc/sudoers.d/octoprint-shutdown
echo "pi ALL=NOPASSWD: /etc/init.d/octoprint" | sudo tee -a /etc/sudoers.d/octoprint-shutdown
su pi -c '/home/pi/OctoPrint/bin/pip install https://github.com/Salandora/octoprint-customControl/archive/master.zip'
su pi -c '/home/pi/OctoPrint/bin/pip install https://github.com/1r0b1n0/OctoPrint-Tempsgraph/archive/master.zip'
su pi -c '/home/pi/OctoPrint/bin/pip install https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/master.zip'
su pi -c '/home/pi/OctoPrint/bin/pip install https://github.com/chatrat12/layerdisplay/archive/master.zip'

apt install -y motion
sed -i '/daemon/s/off/on/' /etc/motion/motion.conf
sed -i '/width/s/320/640/' /etc/motion/motion.conf
sed -i '/height/s/240/480/' /etc/motion/motion.conf
sed -i '/framerate/s/2/15/' /etc/motion/motion.conf
sed -i '/stream_maxrate/s/1/15/' /etc/motion/motion.conf
sed -i '/stream_localhost/s/on/off/' /etc/motion/motion.conf
sed -i '/webcontrol_port/s/8080/0/' /etc/motion/motion.conf



sed -i 'start_motion_daemon/s/no/yes/' /etc/default/motion




